// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatronRepositorio.Data;

#nullable disable

namespace PatronRepositorio.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230531090055_ids")]
    partial class ids
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("PatronRepositorio.Data.Alita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComidaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsMuslito")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreDelPollo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComidaId");

                    b.ToTable("Alita", (string)null);
                });

            modelBuilder.Entity("PatronRepositorio.Data.Comida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Coste")
                        .HasColumnType("REAL");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Venta")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Comida");
                });

            modelBuilder.Entity("PatronRepositorio.Data.Hamburguesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComidaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LlevaPepino")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroCarnes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComidaId");

                    b.ToTable("Hamburguesa", (string)null);
                });

            modelBuilder.Entity("PatronRepositorio.Data.Alita", b =>
                {
                    b.HasOne("PatronRepositorio.Data.Comida", "Comida")
                        .WithMany("Alitas")
                        .HasForeignKey("ComidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comida");
                });

            modelBuilder.Entity("PatronRepositorio.Data.Hamburguesa", b =>
                {
                    b.HasOne("PatronRepositorio.Data.Comida", "Comida")
                        .WithMany("Hamburguesas")
                        .HasForeignKey("ComidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comida");
                });

            modelBuilder.Entity("PatronRepositorio.Data.Comida", b =>
                {
                    b.Navigation("Alitas");

                    b.Navigation("Hamburguesas");
                });
#pragma warning restore 612, 618
        }
    }
}
